;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-newline
        end-of-buffer
        autopair-insert-or-skip-quote
        ess-smart-comma
        ))

(setq mc/cmds-to-run-once
      '(
        ))
